title: "Australian Nextflow Seqera Service"
description: A website for the Australian Nextflow Seqera service
remote_theme: ELIXIR-Belgium/jekyll-bootstrap-theme@2.4.0
topnav_title: Australian Nextflow Seqera Service

theme_variables:
  # biocommons blue
  theme_color: 205a86
  topnav:
    brand_logo: assets/img/Australian-Biocommons-Logo-Horizontal-RGB.png
  privacy_statement_url: https://www.biocommons.org.au/privacy

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar: main
  -
    scope:
      path: "user-guide"
      type: "pages"
    values:
      sidebar: user-guide
    
    
plugins:
  - elixir-toolkit-theme-plugins
